Medkit = Box of Chocolates
Subspace Tripmine = Dev-in-the-Box
Flamethrower = Keythrower
War Horn = Trumpet
Jump Pad = Jolly Man
Grenade = Water Balloon
Molotov = Torch
Flashbang = Glorious Flashbang
Smoke Grenade = Eyeball
Satchel = Glorious Satchel
Warpstone = Starfish Warpstone
Fists = Brass Knuckles
Knife = Pirate Hook
Chainsaw = Blobsaw
Katana = Umbrella
Scythe = Scythe of Death
Trowel = Snow Shovel
Battle Axe = Glorious Battle Axe
Riot Shield = Sled
Maul = Inflatable Hammer
Spear = Glorious Spear
Flare Gun = Banana Flare
Assault Rifle = 10B Visits
Handgun = Blaster
Burst Rifle = Spectral Burst
Sniper = Keyper
RPG = Pencil Launcher
Shorty = Not So Shorty
Shotgun = Wrapped Shotgun
Bow = Bat Bow
Uzi = Water Uzi
Revolver = Desert Eagle
Paintball Gun = Paintballoon Gun
Slingshot = Keyshot
Grenade Launcher = Balloon Launcher
Minigun = Pumpkin Minigun
Exogun = Glorious Exogun
Freeze Ray = Glorious Freeze Ray
Daggers = Keynais
Energy Pistols = New Year Energy Pistols
Energy Rifle = Super Soaker Rifle
Spray = Pine Spray
Crossbow = Frostbite Crossbow
Gunblade = Water Gunblade
