Medkit = Ice Cream
Subspace Tripmine = DIY Tripmine
Flamethrower = Snowblower
War Horn = Air Horn
Jump Pad = Bounce House
Grenade = Jingle Grenade
Molotov = Campfire Stick
Flashbang = Camera
Smoke Grenade = Snowglobe
Satchel = Advanced Satchel
Warpstone = Cyber Warpstone
Fists = Boxing Gloves
Knife = Candy Cane
Chainsaw = Blobsaw
Katana = Arch Katana
Scythe = Anchor
Trowel = Snow Shovel
Battle Axe = Balloon Axe
Riot Shield = Sled
Maul = Ice Maul
Spear = Giant Pencil
Flare Gun = Banana Flare
Assault Rifle = 10B Visits
Handgun = Blaster
Burst Rifle = Pine Burst
Sniper = Event Horizon
RPG = Firework Launcher
Shorty = Balloon Shorty
Shotgun = Balloon Shotgun
Bow = Frostbite Bow
Uzi = Pine Uzi
Revolver = Boneclaw Revolver
Paintball Gun = Snowball Gun
Slingshot = Boneshot
Grenade Launcher = Snowball Launcher
Minigun = Fighter Jet
Exogun = Exogourd
Freeze Ray = Ice Shaver
Daggers = Aces
Energy Pistols = Apex Pistols
Energy Rifle = Apex Rifle
Spray = Pine Spray
Crossbow = Frostbite Crossbow
Gunblade = Boneblade
