Medkit = Box of Chocolates
Subspace Tripmine = DIY Tripmine
Flamethrower = Bubblethrower
War Horn = Boneclaw Horn
Jump Pad = Bounce House
Grenade = Cuddle Bomb
Molotov = Vexed Candle
Flashbang = Skullbang
Smoke Grenade = Balance
Satchel = Advanced Satchel
Warpstone = Cyber Warpstone
Fists = Pumpkin Claws
Knife = Balisong
Chainsaw = Blobsaw
Katana = Evil Trident
Scythe = Bat Scythe
Trowel = Pumpkin Carver
Battle Axe = Glorious Battle Axe
Riot Shield = Boogie Board
Maul = Ban Hammer
Spear = Giant Pencil
Flare Gun = Vexed Flare Gun
Assault Rifle = Boneclaw Rifle
Handgun = Pumpkin Handgun
Burst Rifle = Aqua Burst
Sniper = Event Horizon
RPG = Pumpkin Launcher
Shorty = Demon Shorty
Shotgun = Balloon Shotgun
Bow = Bat Bow
Uzi = Demon Uzi
Revolver = Boneclaw Revolver
Paintball Gun = Boba Gun
Slingshot = Boneshot
Grenade Launcher = Skull Launcher
Minigun = Pumpkin Minigun
Exogun = Exogourd
Freeze Ray = Bubble Ray
Daggers = Bat Daggers
Energy Pistols = Apex Pistols
Energy Rifle = Apex Rifle
Spray = Boneclaw Spray
Crossbow = Crossbone
Gunblade = Boneblade
