Medkit = Box of Chocolates
Subspace Tripmine = DIY Tripmine
Flamethrower = Pixel Flamethrower
War Horn = Air Horn
Jump Pad = Bounce House
Grenade = Cuddle Bomb
Molotov = Campfire Stick
Flashbang = Pixel Flashbang
Smoke Grenade = Balance
Satchel = Advanced Satchel
Warpstone = Cyber Warpstone
Fists = Boxing Gloves
Knife = Balisong
Chainsaw = Blobsaw
Katana = Pixel Katana
Scythe = Anchor
Trowel = Garden Shovel
Battle Axe = Balloon Axe
Riot Shield = Boogie Board
Maul = Ban Hammer
Spear = Giant Pencil
Flare Gun = Banana Flare
Assault Rifle = 10B Visits
Handgun = Pixel Handgun
Burst Rifle = Pixel Burst
Sniper = Pixel Sniper
RPG = Firework Launcher
Shorty = Balloon Shorty
Shotgun = Balloon Shotgun
Bow = Balloon Bow
Uzi = Arch Uzi
Revolver = Boneclaw Revolver
Paintball Gun = Boba Gun
Slingshot = Boneshot
Grenade Launcher = Balloon Launcher
Minigun = Pixel Minigun
Exogun = Exogourd
Freeze Ray = Bubble Ray
Daggers = Aces
Energy Pistols = Apex Pistols
Energy Rifle = Apex Rifle
Spray = Boneclaw Spray
Crossbow = Pixel Crossbow
Gunblade = Boneblade
