Medkit = Box of Chocolates
Subspace Tripmine = DIY Tripmine
Flamethrower = Bubblethrower
War Horn = Air Horn
Jump Pad = Bounce House
Grenade = Water Balloon
Molotov = Campfire Stick
Flashbang = Camera
Smoke Grenade = Balance
Satchel = Advanced Satchel
Warpstone = Cyber Warpstone
Fists = Boxing Gloves
Knife = Water Gun
Chainsaw = Blobsaw
Katana = Arch Katana
Scythe = Palm Tree
Trowel = Garden Shovel
Battle Axe = Balloon Axe
Riot Shield = Boogie Board
Maul = Ban Hammer
Spear = Giant Pencil
Flare Gun = Banana Flare
Assault Rifle = 10B Visits
Handgun = Blaster
Burst Rifle = Water Blaster
Sniper = Event Horizon
RPG = Water Cannon
Shorty = Balloon Shorty
Shotgun = Balloon Shotgun
Bow = Balloon Bow
Uzi = Water Uzi
Revolver = Boneclaw Revolver
Paintball Gun = Paintballoon Gun
Slingshot = Palmshot
Grenade Launcher = Balloon Launcher
Minigun = Fighter Jet
Exogun = Exogourd
Freeze Ray = Bubble Ray
Daggers = Cookies
Energy Pistols = Water Blaster Pistols
Energy Rifle = Apex Rifle
Spray = Boneclaw Spray
Crossbow = Water Crossbow
Gunblade = Water Gunblade
