Medkit = Bucket of Candy
Subspace Tripmine = Spring
Flamethrower = Bubblethrower
War Horn = Boneclaw Horn
Jump Pad = Bounce House
Grenade = Water Balloon
Molotov = Glorious Molotov
Flashbang = Skullbang
Smoke Grenade = Emoji Cloud
Satchel = Glorious Satchel
Warpstone = Electropunk Warpstone
Fists = Fists of Hurt
Knife = Water Gun
Chainsaw = Festive Buzzsaw
Katana = Pixel Katana
Scythe = Glorious Scythe
Trowel = Plastic Shovel
Battle Axe = Cerulean Axe
Riot Shield = Boogie Board
Maul = Glorious Maul
Spear = Glorious Spear
Flare Gun = Banana Flare
Assault Rifle = AK-47
Handgun = Pumpkin Handgun
Burst Rifle = FAMAS
Sniper = Hyper Sniper
RPG = Glorious RPG
Shorty = Squirt Pistol
Shotgun = Super Soaker
Bow = Sunburst Bow
Uzi = Electro Uzi
Revolver = Desert Eagle
Paintball Gun = Boba Gun
Slingshot = Goalpost
Grenade Launcher = Uranium Launcher
Minigun = Glorious Minigun
Exogun = Exogourd
Freeze Ray = Gum Ray
Daggers = Popsicles
Energy Pistols = Hacker Pistols
Energy Rifle = New Year Energy Rifle
Spray = Pine Spray
Crossbow = Pixel Crossbow
Gunblade = Elf's Gunblade
