Medkit = Glorious Medkit
Subspace Tripmine = Glorious Subspace Tripmine
Flamethrower = Glorious Flamethrower
War Horn = Glorious War Horn
Jump Pad = Glorious Jump Pad
Grenade = Glorious Grenade
Molotov = Glorious Molotov
Flashbang = Glorious Flashbang
Smoke Grenade = Glorious Smoke Grenade
Satchel = Glorious Satchel
Warpstone = Glorious Warpstone
Fists = Glorious Fists
Knife = Glorious Knife
Chainsaw = Glorious Chainsaw
Katana = Glorious Katana
Scythe = Glorious Scythe
Trowel = Glorious Trowel
Battle Axe = Glorious Battle Axe
Riot Shield = Glorious Riot Shield
Maul = Glorious Maul
Spear = Glorious Spear
Flare Gun = Glorious Flare Gun
Assault Rifle = Glorious Assault Rifle
Handgun = Glorious Handgun
Burst Rifle = Glorious Burst Rifle
Sniper = Glorious Sniper
RPG = Glorious RPG
Shorty = Glorious Shorty
Shotgun = Glorious Shotgun
Bow = Glorious Bow
Uzi = Glorious Uzi
Revolver = Glorious Revolver
Paintball Gun = Glorious Paintball Gun
Slingshot = Glorious Slingshot
Grenade Launcher = Glorious Grenade Launcher
Minigun = Glorious Minigun
Exogun = Glorious Exogun
Freeze Ray = Glorious Freeze Ray
Daggers = Glorious Daggers
Energy Pistols = Glorious Energy Pistols
Energy Rifle = Glorious Energy Rifle
Spray = Glorious Spray
Crossbow = Glorious Crossbow
Gunblade = Glorious Gunblade
