Medkit = Box of Chocolates
Subspace Tripmine = Pot o' Keys
Flamethrower = Keythrower
War Horn = Air Horn
Jump Pad = Bounce House
Grenade = Cuddle Bomb
Molotov = Campfire Stick
Flashbang = Camera
Smoke Grenade = Balance
Satchel = Advanced Satchel
Warpstone = Cyber Warpstone
Fists = Boxing Gloves
Knife = Keylisong
Chainsaw = Blobsaw
Katana = Keytana
Scythe = Keythe
Trowel = Garden Shovel
Battle Axe = Keyttle Axe
Riot Shield = Boogie Board
Maul = Ban Hammer
Spear = Giant Pencil
Flare Gun = Banana Flare
Assault Rifle = AKEY-47
Handgun = Blaster
Burst Rifle = Keyst Rifle
Sniper = Keyper
RPG = RPKEY
Shorty = Balloon Shorty
Shotgun = Balloon Shotgun
Bow = Key Bow
Uzi = Keyzi
Revolver = Boneclaw Revolver
Paintball Gun = Boba Gun
Slingshot = Keyshot
Grenade Launcher = Balloon Launcher
Minigun = Fighter Jet
Exogun = Exogourd
Freeze Ray = Bubble Ray
Daggers = Keynais
Energy Pistols = Apex Pistols
Energy Rifle = Apex Rifle
Spray = Key Spray
Crossbow = Crossbone
Gunblade = Boneblade
