Medkit = Box of Chocolates
Subspace Tripmine = DIY Tripmine
Flamethrower = Bubblethrower
War Horn = Air Horn
Jump Pad = Bounce House
Grenade = Cuddle Bomb
Molotov = Campfire Stick
Flashbang = Camera
Smoke Grenade = Balance
Satchel = Advanced Satchel
Warpstone = Cyber Warpstone
Fists = Boxing Gloves
Knife = Balisong
Chainsaw = Blobsaw
Katana = Crystal Katana
Scythe = Crystal Scythe
Trowel = Garden Shovel
Battle Axe = Balloon Axe
Riot Shield = Boogie Board
Maul = Ban Hammer
Spear = Giant Pencil
Flare Gun = Banana Flare
Assault Rifle = Pearl Rifle
Handgun = Stealth Handgun
Burst Rifle = Aqua Burst
Sniper = Event Horizon
RPG = Firework Launcher
Shorty = Balloon Shorty
Shotgun = Balloon Shotgun
Bow = Balloon Bow
Uzi = Arch Uzi
Revolver = Boneclaw Revolver
Paintball Gun = Boba Gun
Slingshot = Boneshot
Grenade Launcher = Balloon Launcher
Minigun = Fighter Jet
Exogun = Exogourd
Freeze Ray = Bubble Ray
Daggers = Shurikens
Energy Pistols = Apex Pistols
Energy Rifle = Apex Rifle
Spray = Boneclaw Spray
Crossbow = Crossbone
Gunblade = Boneblade
