Medkit = Box of Chocolates
Subspace Tripmine = DIY Tripmine
Flamethrower = Bubblethrower
War Horn = Air Horn
Jump Pad = Bounce House
Grenade = Cuddle Bomb
Molotov = Campfire Stick
Flashbang = Camera
Smoke Grenade = Balance
Satchel = Advanced Satchel
Warpstone = Cyber Warpstone
Fists = Boxing Gloves
Knife = Balisong
Chainsaw = Blobsaw
Katana = Arch Katana
Scythe = Anchor
Trowel = Garden Shovel
Battle Axe = Balloon Axe
Riot Shield = Boogie Board
Maul = Ban Hammer
Spear = Giant Pencil
Flare Gun = Banana Flare
Assault Rifle = 10B Visits
Handgun = Blaster
Burst Rifle = Electro Rifle
Sniper = Event Horizon
RPG = Firework Launcher
Shorty = Balloon Shorty
Shotgun = Balloon Shotgun
Bow = Balloon Bow
Uzi = Electro Uzi
Revolver = Boneclaw Revolver
Paintball Gun = Boba Gun
Slingshot = Boneshot
Grenade Launcher = Balloon Launcher
Minigun = Fighter Jet
Exogun = Repulsor
Freeze Ray = Bubble Ray
Daggers = Aces
Energy Pistols = Apex Pistols
Energy Rifle = Apex Rifle
Spray = Boneclaw Spray
Crossbow = Crossbone
Gunblade = Boneblade
